# Site
name: 'ScaleDown'
description: 'ScaleDown is an Open-Source Neural Network Optimization Framework for TinyML'
logo: 'assets/images/side_text_logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'blog'
# disqus: 'demowebsite'
email: 'hello@csoham.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    soham:
      name:           Soham
      site:           https://www.csoham.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Soham! "
      email:          hello@csoham.com
      twitter:        https://twitter.com/csoham_

    archana:
      name:           Archana
      site:           https://www.varchanaiyer.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Archana!"
      email:          varchanaiyer139@gmail.com
      twitter:        https://twitter.com/varchanaiyer_
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: scaledown
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
